[package]
name = "squash_the_creeps"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext.git", features = ["register-docs", "api-4-4"] }


serde = "*"
serde_derive = "*"
serde_json = "*"
